### ISSUE TITLE
Error when typing emojies

### ISSUE THREAD

**Issue by morajabi** [sallar/led-matrix-simulator#1]
You can filter non standard characters (chars which aren't in your font) so it won't break.

![screen shot 2016-12-03 at 4 33 01 pm](https://cloud.githubusercontent.com/assets/12202757/20859497/3f1fb7d6-b976-11e6-9e7b-bddbd1cf39e9.png)

**Comment by sallar** [comment]
Thansk @morajabi, fixed.
